/var/log/nginx/monitoring.json {
    daily
    rotate 7
    missingok
    notifempty
    nocompress
    create 0640 www-data adm
    sharedscripts
    postrotate
        /usr/sbin/nginx -s reopen
    endscript
}
